[workspace]
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
]
platforms = ["linux-64"]
preview = ["pixi-build"]
license = "CECILL-C"

# dependencies of the "default" feature: add the package, it will pull in its run-time dependencies!
[dependencies]
example = { path = "." }

[package]
name = "example" # NAME_PLACEHOLDER <--- do not remove this comment! It is used to update version with branch name in CI!
version = "0.1.0" # VERSION_PLACEHOLDER <--- do not remove this comment! It is used to update version with branch name in CI!
authors = [
    "Vincent Pollet <vincent.pollet@lapp.in2p3.fr>",
]

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }


[package.build-dependencies]
# sigtool = ">=0.1.3,<0.2"

[package.target.osx-64.build-dependencies]
sigtool = ">=0.1.3,<0.2"

[package.host-dependencies]

[package.run-dependencies]
