[workspace]
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
]
platforms = ["linux-64", "osx-arm64"]
preview = ["pixi-build"]
license = "MIT"

[dependencies]
example = { path = "." }

[package]
name = "example"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.9.*" }


[package.build-dependencies]
# sigtool = ">=0.1.3,<0.2"

[package.target.osx-64.build-dependencies]
sigtool = ">=0.1.3,<0.2"

[package.host-dependencies]

[package.run-dependencies]
